import itemManagement as m
import keyboard as k

k.add_hotkey('shift+enter',m.buatDiskon_obo)
k.add_hotkey('f5',m.refresh)
m.screen.config(bg="khaki")
m.screen.resizable(False,False)

L_jdl = m.c.tk.Label(m.screen, text="ITEM MANAGEMENT")
L_jdl.grid(row=0,column=0,columnspan=10,pady=8)
L_jdl.config(bg='navy',font=('Arial-Bold',17),fg='whitesmoke')

L_a = m.c.tk.Label(m.screen, text="")
L_a.grid(row=1,column=0,pady=3)
L_a.config(bg='khaki')

L_barcode = m.c.tk.Label(m.screen,text="BARCODE")
L_barcodeA = m.c.tk.Label(m.screen,text=":")
E_barcode = m.c.tk.Entry(m.screen,textvariable=m.barcode)
L_barcode.grid(row=2,column=0,sticky='w',pady=3)
L_barcodeA.grid(row=2,column=1)
E_barcode.grid(row=2,column=2,sticky='we')
L_barcode.config(font=('Arial',12),bg='khaki')
L_barcodeA.config(font=('Arial',12),bg='khaki')
E_barcode.config(font=('Arial',12))

L_startDate = m.c.tk.Label(m.screen,text="DARI TANGGAL (YYYY-MM-DD)")
L_startDateA = m.c.tk.Label(m.screen,text=":")
E_startDate = m.c.tk.Entry(m.screen,textvariable=m.startDate)
L_startDate.grid(row=3,column=0,sticky='w',pady=3)
L_startDateA.grid(row=3,column=1)
E_startDate.grid(row=3,column=2,sticky='we')
L_startDate.config(font=('Arial',12),bg='khaki')
L_startDateA.config(font=('Arial',12),bg='khaki')
E_startDate.config(font=('Arial',12))

L_endDate = m.c.tk.Label(m.screen,text="SAMPAI TANGGAL (YYYY-MM-DD)")
L_endDateA = m.c.tk.Label(m.screen,text=":")
E_endDate = m.c.tk.Entry(m.screen,textvariable=m.endDate)
L_endDate.grid(row=4,column=0,sticky='w',pady=3)
L_endDateA.grid(row=4,column=1)
E_endDate.grid(row=4,column=2,sticky='we')
L_endDate.config(font=('Arial',12),bg='khaki')
L_endDateA.config(font=('Arial',12),bg='khaki')
E_endDate.config(font=('Arial',12))

L_disc = m.c.tk.Label(m.screen,text="DISCOUNT")
L_discA = m.c.tk.Label(m.screen,text=":")
L_discB = m.c.tk.Label(m.screen,text="%")
E_disc = m.c.tk.Entry(m.screen,textvariable=m.disc)
L_disc.grid(row=5,column=0,sticky='w',pady=3)
L_discA.grid(row=5,column=1)
E_disc.grid(row=5,column=2,sticky='we')
L_discB.grid(row=5,column=3)
L_disc.config(font=('Arial',12),bg='khaki')
L_discA.config(font=('Arial',12),bg='khaki')
L_discB.config(font=('Arial',12),bg='khaki')
E_disc.config(font=('Arial',12))

L_ket = m.c.tk.Label(m.screen,text="KETERANGAN")
L_ketA = m.c.tk.Label(m.screen,text=":")
E_ket = m.c.tk.Entry(m.screen,textvariable=m.ket)
L_ket.grid(row=6,column=0,sticky='w',pady=3)
L_ketA.grid(row=6,column=1)
E_ket.grid(row=6,column=2,sticky='we')
L_ket.config(font=('Arial',12),bg='khaki')
L_ketA.config(font=('Arial',12),bg='khaki')
E_ket.config(font=('Arial',12))

m.view['column'] = ("f_barcode","f_merk","f_nama","f_harga")
m.view.column("#0",width=40,stretch="NO")
m.view.column('f_barcode',width=120)
m.view.column('f_merk',width=120)
m.view.column('f_nama',width=120)
m.view.column('f_harga',width=120)
m.view.heading('#0',text="")
m.view.heading('f_barcode', text="barcode")
m.view.heading('f_merk',text="Merk Produk")
m.view.heading('f_nama',text="Nama Produk")
m.view.heading('f_harga', text="Harga Berlaku (Rp.)")
m.view.grid(row=7,column=0,columnspan=4,rowspan=10,pady=5,sticky='nswe')

B_all_dis = m.c.tk.Button(m.screen,text="DISCOUNT ALL PRODUCT\n[require supervisor PIN]",command=m.buatDiskon_all_item)
B_obo_dis = m.c.tk.Button(m.screen,text="DISCOUNT PRODUCT\n[press SHIFT+ENTER]",command=m.buatDiskon_obo)
B_refresh = m.c.tk.Button(m.screen,text="REFRESH\n[press F5]",command=m.refresh)
B_all_dis.grid(row=2,column=4,rowspan=2,sticky='ewns')
B_obo_dis.grid(row=4,column=4,rowspan=2,sticky='ewns')
B_refresh.grid(row=6,column=4,rowspan=2,sticky='ewns')
B_all_dis.config(bg='darkkhaki',fg='black',font=('Helvetica-Bold',12))
B_obo_dis.config(bg='darkkhaki',fg='black',font=('Helvetica-Bold',12))
B_refresh.config(bg='darkkhaki',fg='black',font=('Helvetica-Bold',12))

m.screen.mainloop()